ARCHS = arm64 arm64e
TARGET = iphone:clang:14.4:13
INSTALL_TARGET_PROCESSES = Recents

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = Recents

Recents_FILES = AppDelegate.swift RootViewController.swift
Recents_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
